name: KLEE Analysis

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  klee-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg REPO_URL=${{ github.event.repository.clone_url }} \
          --build-arg REPO_BRANCH=${{ github.ref_name }} \
          -t klee-coreutils .

    - name: Prepare workspace for KLEE output
      run: |
        mkdir -p ${{ github.workspace }}/klee-out-example1
        chmod -R 777 ${{ github.workspace }}/klee-out-example1

    - name: Run KLEE Analysis
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace klee-coreutils /bin/bash -c "
          mkdir -p /home/klee/tmp && \
          klee --output-dir=/home/klee/tmp/klee-out-example1 --libc=uclibc --posix-runtime /coreutils/obj-llvm/src/echo.bc --sym-arg 7 && \
          cp -r /home/klee/tmp/klee-out-example1 /workspace/klee-out-example1
        "

    - name: Upload KLEE Output
      uses: actions/upload-artifact@v3
      with:
        name: klee-results
        path: ./klee-out-example1